export const IconFamily = {
  antDesign: 'AntDesign',
  entypo: 'Entypo',
  evilIcons: 'EvilIcons',
  feather: 'Feather',
  fontAwesome: 'FontAwesome',
  fontAwesome5: 'FontAwesome5',
  fontAwesome5Brands: 'FontAwesome5Brands',
  FONT_AWESOME6: 'FontAwesome6',
  FONT_AWESOME6Brands: 'FontAwesome6Brands',
  FONTISTO: 'Fontisto',
  FOUNDATION: 'Foundation',
  IONICONS: 'Ionicons',
  MATERIAL_COMMUNITY_ICONS: 'MaterialCommunityIcons',
  MATERIAL_ICONS: 'MaterialIcons',
  OCTICONS: 'Octicons',
  SIMPLE_LINE_ICONS: 'SimpleLineIcons',
  ZOCIAL: 'Zocial',
} as const;

export const Icons = {
  antDesign: {},
  entypo: {},
  evilIcons: {},
  feather: {},
  fontAwesome: {},
  fontAwesome5: {},
  fontAwesome5Brands: {},
  fontAwesome6: {},
  fontAwesome6Brands: {},
  fontisto: {},
  foundation: {},
  ionicons: {},
  materialCommunityIcons: {},
  materialIcons: {},
  octicons: {},
  simpleLineIcons: {},
  zocial: {},
};
