export const Opacity = {
  level1: 0.08,
  level2: 0.12,
  level3: 0.16,
  level4: 0.38,
  full: 1,
} as const;

export const ColorType = {
  primary: 'primary',
  primaryContainer: 'primaryContainer',
  secondary: 'secondary',
  secondaryContainer: 'secondaryContainer',
  tertiary: 'tertiary',
  tertiaryContainer: 'tertiaryContainer',
  error: 'error',
  errorContainer: 'errorContainer',
  background: 'background',
  onPrimary: 'onPrimary',
  onPrimaryContainer: 'onPrimaryContainer',
  onSecondary: 'onSecondary',
  onSecondaryContainer: 'onSecondaryContainer',
  onTertiary: 'onTertiary',
  onTertiaryContainer: 'onTertiaryContainer',
  onError: 'onError',
  onErrorContainer: 'onErrorContainer',
  onBackground: 'onBackground',
  onSurface: 'onSurface',
  onSurfaceVariant: 'onSurfaceVariant',
  onSurfaceDisabled: 'onSurfaceDisabled',
  surface: 'surface',
  surfaceDim: 'surfaceDim',
  surfaceBright: 'surfaceBright',
  surfaceContainerLowest: 'surfaceContainerLowest',
  surfaceContainerLow: 'surfaceContainerLow',
  surfaceContainer: 'surfaceContainer',
  surfaceContainerHigh: 'surfaceContainerHigh',
  surfaceContainerHighest: 'surfaceContainerHighest',
  outline: 'outline',
  outlineVariant: 'outlineVariant',
  shadow: 'shadow',
  scrim: 'scrim',
  inverseSurface: 'inverseSurface',
  inverseOnSurface: 'inverseOnSurface',
  inversePrimary: 'inversePrimary',
  backdrop: 'backdrop',
  transparent: 'transparent',
} as const;
